import fs from "node:fs";
import path from "node:path";
import cp from "node:child_process";

import { FunctionDecl, getNodeApiFunctions } from "./node-api-functions";

export const CPP_SOURCE_PATH = path.join(__dirname, "../cpp");

/**
 * Generates source code which injects the Node API functions from the host.
 */
export function generateSource(functions: FunctionDecl[]) {
  return `
    // This file is generated by react-native-node-api-modules
    #include <Logger.hpp>
    #include <dlfcn.h>
    #include <weak_node_api.hpp>

    #if defined(__APPLE__)
    #define WEAK_NODE_API_LIBRARY_NAME "@rpath/weak-node-api.framework/weak-node-api"
    #elif defined(__ANDROID__)
    #define WEAK_NODE_API_LIBRARY_NAME "libweak-node-api.so"
    #else
    #error "WEAK_NODE_API_LIBRARY_NAME cannot be defined for this platform"
    #endif

    namespace callstack::nodeapihost {
    
    using node_api::internal::inject_host_t;
    using node_api::internal::NodeApiHost;

    void injectIntoWeakNodeApi() {
    void *module = dlopen(WEAK_NODE_API_LIBRARY_NAME, RTLD_NOW | RTLD_LOCAL);
    if (NULL == module) {
      log_debug("NapiHost: Failed to load weak-node-api: %s", dlerror());
      abort();
    }

    auto inject_host = (inject_host_t)dlsym(
        module, "_ZN8node_api8internal11inject_hostERKNS0_11NodeApiHostE");
    if (NULL == inject_host) {
      log_debug("NapiHost: Failed to find 'inject_host' function: %s", dlerror());
      abort();
    }

    log_debug("Injecting WeakNodeApiHost");
    inject_host(NodeApiHost {
      ${functions
        .filter(({ kind }) => kind === "engine")
        .flatMap(({ name }) => `.${name} = ${name},`)
        .join("\n")}
      });
    }
    } // namespace callstack::nodeapihost
  `;
}

async function run() {
  const nodeApiFunctions = getNodeApiFunctions();

  const source = generateSource(nodeApiFunctions);
  const sourcePath = path.join(CPP_SOURCE_PATH, "WeakNodeApiInjector.cpp");
  await fs.promises.writeFile(sourcePath, source, "utf-8");
  cp.spawnSync("clang-format", ["-i", sourcePath], { stdio: "inherit" });
}

run().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
